### ISSUE TITLE
Error: ERR wrong number of arguments for 'set' command

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mDraw#10]
[Error: ERR wrong number of arguments for 'set' command]
broadcasting to all
updating
Added container to your board successfully!
broadcasting to all

**Comment by caninojories** [comment]
can you give exact step by step details.. so that i can replicate it in my localhost?

**Comment by bluenevus** [comment]
All I did was launch a board with a name like frank, then dragged and dropped a table on the canvas

## 

Vr Frank

**Comment by bluenevus** [comment]
fixed
