### ISSUE TITLE
save to disk and upload image

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mDraw#14]
the user should have the ability to save the drawing to local hard drive.  At a future time, the user should be able to then upload that image into a different link and resume their drawing.

**Comment by bluenevus** [comment]
save to disk works however uploading to the server does not resume canvas.  Also, the option to upload a saved canvas should appear on the home screen where  users first launch and/or when the canvas size pops up.  certainly when the canvas size dialog pops up as the user is most likely to choose to upload a saved canvas there.  in any case, uploading doesn't work and does not resume canvas

**Comment by caninojories** [comment]
did you make an npm install after pulling?

**Comment by bluenevus** [comment]
Yes…fresh install with the previous uninstalled

Test it here https://draw.microhealthllc.com

## 

Vr Frank

**Comment by caninojories** [comment]
can you git pull again.. thanks

**Comment by bluenevus** [comment]
sure

## 

Vr Frank

**Comment by bluenevus** [comment]
canvas uploaded to  uploads/data (20)1436150668755.json
/usr/share/mDraw/app.js:264
          for(var i = 0; i < obj.shapeModel.length; i++) {
                                           ^
TypeError: Cannot read property 'length' of undefined
    at /usr/share/mDraw/app.js:264:44
    at /usr/share/mDraw/node_modules/jsonfile/index.js:19:5
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)

**Comment by bluenevus** [comment]
broadcasting to all
eventDraw in line no. 33 [object Object]
{ name: 'Nohm Error',
  message: 'Expected 1, found 2shapes for (shapeId):wgsDkLax1436150613302' }
eventDraw in line no. 33 [object Object]
{ name: 'Nohm Error',
  message: 'Expected 1, found 2shapes for (shapeId):U2m4yQT41436150615344' }
zlvnxdu4.json is starting ...
canvas uploaded to  uploads/zlvnxdu41436150787105.json
broadcasting to all

**Comment by bluenevus** [comment]
doesn't work.  uploading results in the error above.  looks like its uploading.  the screen refreshes then its blank

**Comment by bluenevus** [comment]
fresh pull.. here are the errors.  Clicked save and it blew up.

Nohm Connected to Redis Client
[Error: ERR wrong number of arguments for 'set' command]
broadcasting to all
eventDraw in line no. 33 [object Object]
setContainer in line no. 28 [object Object]
updating
Added container to your board successfully!
eventDraw in line no. 33 [object Object]
eventDraw in line no. 33 [object Object]
eventDraw in line no. 33 [object Object]
load shape in line no. 106
eventDraw in line no. 33 [object Object]
load shape in line no. 106
eventDraw in line no. 33 [object Object]
fs.js:77
      throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs
            ^
Error: ENOENT, open '/usr/share/mDraw/tmp/muhf6a6h.json'
    at Error (native)

**Comment by caninojories** [comment]
hello.. i added temporary.. tmp and upload data.. so that it would avoid ENOENT.. can pull again? thank you

**Comment by bluenevus** [comment]
working
